#!/bin/bash

# if [ $EUID != 0 ]
# then
#     echo -e "\e[5m\e[1;41mNecesita ejecutar el programa con permisos de administrador\e[0m"
#     exit 1
# fi

lines=$(awk 'END{ print NR }' packages.dat)

[ ! -d $HOME/.logs ] && mkdir $HOME/.logs

installed="./.installed.dat"
skipped="./.skipped.dat"
aptMeslog="$HOME/.logs/aptMeslog.install.log"
aptError="$HOME/.logs/aptError.install.log"
aptSuccess="$HOME/.logs/aptSuccess.install.log"
snapMeslog="$HOME/.logs/snapMeslog.install.log"
snapError="$HOME/.logs/snapError.install.log"
snapSuccess="$HOME/.logs/snapSuccess.install.log"
flatpakMeslog="$HOME/.logs/flatpakMeslog.install.log"
flatpakError="$HOME/.logs/flatpakError.install.log"
flatpakSuccess="$HOME/.logs/flatpakSuccess.install.log"

[ ! -f $installed ] && touch $installed && echo -e "\e[1;43m[i] Archivo .installed.dat creado\e[0m"
[ ! -f $skipped ] && touch $skipped && echo -e "\e[1;43m[i] Archivo .skipped.dat creado\e[0m"

[ ! -f $aptMeslog ] && touch $aptMeslog && echo -e "\e[1;43m[i] Archivo aptMeslog.log creado\e[0m"
[ ! -f $aptError ] && touch $aptError && echo -e "\e[1;43m[i] Archivo aptError.log creado\e[0m"
[ ! -f $aptSuccess ] && touch $aptSuccess && echo -e "\e[1;43m[i] Archivo aptSuccess.log creado\e[0m"

[ ! -f $flatpakMeslog ] && touch $flatpakMeslog && echo -e "\e[1;43m[i] Archivo flatpakMeslog.log creado\e[0m"
[ ! -f $flatpakError ] && touch $flatpakError && echo -e "\e[1;43m[i] Archivo flatpakError.log creado\e[0m"
[ ! -f $flatpakSuccess ] && touch $flatpakSuccess && echo -e "\e[1;43m[i] Archivo flatpakSuccess.log creado\e[0m"

[ ! -f $snapMeslog ] && touch $snapMeslog && echo -e "\e[1;43m[i] Archivo snapMeslog.log creado\e[0m"
[ ! -f $snapError ] && touch $snapError && echo -e "\e[1;43m[i] Archivo snapError.log creado\e[0m"
[ ! -f $snapSuccess ] && touch $snapSuccess && echo -e "\e[1;43m[i] Archivo snapSuccess.log creado\e[0m"

for (( i=2; i<=$lines; i++))
do
    name=$(awk -F , 'NR == line { print $1 }' line=$i packages.dat | sed 's/\s*$//g' | xargs -I % echo %)
    aptName=$(awk -F , 'NR == line { print $2 }' line=$i packages.dat | sed 's/\s*$//g' | xargs -I % echo %)
    snapName=$(awk -F , 'NR == line { print $3 }' line=$i packages.dat | sed 's/\s*$//g' | xargs -I % echo %)
    flatpakName=$(awk -F , 'NR == line { print $4 }' line=$i packages.dat | sed 's/\s*$//g' | xargs -I % echo %)
    description=$(awk -F , 'NR == line { print $5 }' line=$i packages.dat | sed 's/\s*$//g' | xargs -I % echo %)

    grep "$name" $installed &>/dev/null; found=$?
    [ $found -eq 0 ] && echo -e "\n\e[1;42m[+] Paquete \"$name\" instalado\e[0m" && continue

    grep "$name" $skipped &>/dev/null; skip=$?
    [ $skip -eq 0 ] && echo -e "\n\e[1;43m[i] Paquete \"$name\" saltado\e[0m" && continue

    echo -e "\e[1;35m\n[?] Instalar paquete \"$name\"?...\e[0m"
    echo -e "\e[1;36mDescripcion: $description\e[0m"
    read -n 1 -p "[S/n]: " ans

    if [[ $ans == "" || $ans == "S" || $ans == "s" ]]
    then
        true
    else
        echo -e "\n\e[1;43m[!] Saltando instalación del paquete \"$name\"\e[0m"
        echo -e $name >> $skipped
        continue
    fi

    echo -e "\n\e[1;44m[*] Instalando con aptitude\e[0m" | tee -a $aptMeslog
    [[ $aptName != "" ]] && sudo apt install -y $aptName 2>/dev/null; STATUS=$?
    if [ $STATUS -ne 0 ]
    then
        echo -e "\n\e[1;41m[!] Error al instalar el paquete \"$name\" con aptitude\e[0m" | tee -a $aptError
        success=0
    else
        echo -e "\n\e[1;42m[+] Paquete \"$name\" instalado correctamente con aptitude\e[0m" | tee -a $aptSuccess
        echo -e $name >> $installed
        success=1
    fi

    if [ $success -eq 0 ]
    then
        echo -e "\n\e[1;44m[*] Instalando con Flatpak\e[0m" | tee -a $flatpakMeslog
        [[ $flatpakName != "" ]] && flatpak install -y $flatpakName 2>/dev/null; STATUS=$?
        if [ $STATUS -ne 0 ]
        then
            echo -e "\n\e[1;41m[!] Error al instalar el paquete \"$name\" con Flatpak\e[0m" | tee -a $flatpakError
        else
            echo -e "\n\e[1;42m[+] Paquete \"$name\" instalado correctamente con Flatpak\e[0m" | tee -a $flatpalSuccess
            echo -e $name >> $installed
            success=1
        fi
    fi

    if [ $success -eq 0 ]
    then
        echo -e "\n\e[1;44m[*] Instalando con snap\e[0m" | tee -a $snapMeslog
        [[ $snapName != "" ]] && sudo snap install $snapName 2>/dev/null; STATUS=$?
        if [ $STATUS -ne 0 ]
        then
            echo -e "\n\e[1;41m[!] Error al instalar el paquete \"$name\" con snap\e[0m" | tee -a $snapError
        else
            echo -e "\n\e[1;42m[+] Paquete \"$name\" instalado correctamente con snap\e[0m" | tee -a $snapSuccess
            echo -e $name >> $installed
            success=1
        fi
    fi

done

