#!/bin/bash

# if [ $EUID != 0 ]
# then
#     echo -e "\e[5m\e[1;41mNecesita ejecutar el programa con permisos de administrador\e[0m"
#     exit 1
# fi

lines=$(awk 'END{ print NR }' packages.dat)

[ ! -d $HOME/.logs ] && mkdir $HOME/.logs

aptMeslog="$HOME/.logs/aptMeslog.install.log"
aptError="$HOME/.logs/aptError.install.log"
aptSuccess="$HOME/.logs/aptSuccess.install.log"
snapMeslog="$HOME/.logs/snapMeslog.install.log"
snapError="$HOME/.logs/snapError.install.log"
snapSuccess="$HOME/.logs/snapSuccess.install.log"
flatpakMeslog="$HOME/.logs/flatpakMeslog.install.log"
flatpakError="$HOME/.logs/flatpakError.install.log"
flatpakSuccess="$HOME/.logs/flatpakSuccess.install.log"

[ -f $aptMeslog ] && rm $aptMeslog
touch $aptMeslog && echo -e "\e[1;43m[i] Archivo aptMeslog.log creado\e[0m"

[ -f $aptError ] && rm $aptError
touch $aptError && echo -e "\e[1;43m[i] Archivo aptError.log creado\e[0m"

[ -f $aptSuccess ] && rm $aptSuccess
touch $aptSuccess && echo -e "\e[1;43m[i] Archivo aptSuccess.log creado\e[0m"

[ -f $snapMeslog ] && rm $snapMeslog
touch $snapMeslog && echo -e "\e[1;43m[i] Archivo snapMeslog.log creado\e[0m"

[ -f $snapError ] && rm $snapError
touch $snapError && echo -e "\e[1;43m[i] Archivo snapError.log creado\e[0m"

[ -f $snapSuccess ] && rm $snapSuccess
touch $snapSuccess && echo -e "\e[1;43m[i] Archivo snapSuccess.log creado\e[0m"

[ -f $flatpakMeslog ] && rm $flatpakMeslog
touch $flatpakMeslog && echo -e "\e[1;43m[i] Archivo flapatkMeslog.log creado\e[0m"

[ -f $flatpakError ] && rm $flatpakError
touch $flatpakError && echo -e "\e[1;43m[i] Archivo flatpakError.log creado\e[0m"

[ -f $flatpakSuccess ] && rm $flatpakSuccess
touch $flatpakSuccess && echo -e "\e[1;43m[i] Archivo flatpakSuccess.log creado\e[0m"

for (( i=2; i<=$lines; i++))
do
    name=$(awk -F , 'NR == line { print $1 }' line=$i packages.dat | sed 's/\s*$//g' | xargs -I % echo %)
    aptName=$(awk -F , 'NR == line { print $2 }' line=$i packages.dat | sed 's/\s*$//g' | xargs -I % echo %)
    snapName=$(awk -F , 'NR == line { print $3 }' line=$i packages.dat | sed 's/\s*$//g' | xargs -I % echo %)
    flatpakName=$(awk -F , 'NR == line { print $4 }' line=$i packages.dat | sed 's/\s*$//g' | xargs -I % echo %)
    description=$(awk -F , 'NR == line { print $5 }' line=$i packages.dat | sed 's/\s*$//g' | xargs -I % echo %)

    echo -e "\e[1;35m\n[?] Instalar paquete \"$name\"?...\e[0m"
    echo -e "\e[1;36mDescripcion: $description\e[0m"
    read -n 1 -p "[S/n]: " ans

    if [[ $ans == "" || $ans == "S" || $ans == "s" ]]
    then
        true
    else
        echo -e "\n\e[1;43m[!] Saltando instalación del paquete \"$name\"\e[0m"
        continue
    fi

    echo -e "\n\e[1;44m[*] Instalando con aptitude\e[0m" | tee $aptMeslog
    [[ $aptName != "" ]] && sudo apt install -y $aptName 2>/dev/null; STATUS=$?
    if [ $STATUS -ne 0 ]
    then
        echo -e "\n\e[1;41m[!] Error al instalar el paquete \"$name\" con aptitude\e[0m" | tee $aptError
        success=0
    else
        echo -e "\n\e[1;42m[+] Paquete \"$name\" instalado correctamente con aptitude\e[0m" | tee $aptSuccess
        success=1
    fi

    if [ $success -eq 0 ]
    then
        echo -e "\n\e[1;44m[*] Instalando con snap\e[0m" | tee $snapMeslog
        [[ $snapName != "" ]] && sudo snap install $snapName 2>/dev/null; STATUS=$?
        if [ $STATUS -ne 0 ]
        then
            echo -e "\n\e[1;41m[!] Error al instalar el paquete \"$name\" con snap\e[0m" | tee $snapError
        else
            echo -e "\n\e[1;42m[+] Paquete \"$name\" instalado correctamente con snap\e[0m" | tee $snapSuccess
            success=1
        fi
    fi

    if [ $success -eq 0 ]
    then
        echo -e "\n\e[1;44m[*] Instalando con Flatpak\e[0m" | tee $flatpakMeslog
        [[ $flatpakName != "" ]] && flatpak install -y $flatpakName 2>/dev/null; STATUS=$?
        if [ $STATUS -ne 0 ]
        then
            echo -e "\n\e[1;41m[!] Error al instalar el paquete \"$name\" con Flatpak\e[0m" | tee $flatpakError
        else
            echo -e "\n\e[1;42m[+] Paquete \"$name\" instalado correctamente con Flatpak\e[0m" | tee $flatpalSuccess
            success=1
        fi
    fi

done

