#!/bin/bash

sudo apt update
sudo apt upgrade

echo -e "\n\e[1;44m[*] Instalando y configurando flatpak\e[0m"
sudo apt install -y flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
mkdir -p ~/.themes
cp -a /usr/share/themes/* ~/.themes/
sudo flatpak override --filesystem=~/.themes/
echo -e "\n\e[1;42m[+] Instalación y configuración de Flatpak completada\e[0m"

echo -e "\n\e[1;44m[*] Instalando y configurando snap\e[0m"
sudo apt install -y snapd
sudo systemctl enable --now snapd apparmor
echo -e "\n\e[1;42m[+] Instalación y configuración de snap completada\e[0m"

